### ISSUE TITLE
Automate builds with Netlify

### ISSUE THREAD

**Issue by dzygmundfelt** [phillycommunitywireless/map#12]

**Comment by addiebarron** [comment]
Asking my friend at Netlify about setting this up. Seems easy enough.

**Comment by addiebarron** [comment]
So Netlify looks like a nice and solid choice for hosting a Gatsby site, but I don't think it supports scheduled / regular builds, or builds that trigger on a data source change. 

The simplest approach I can find would be using [a Github Action with the `schedule` option](https://futurestud.io/tutorials/github-actions-trigger-builds-on-schedule-cron) to rebuild the site regularly. I can work on setting this up
